# Deployment cho web1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: ttldlinhtm/web1:latest
        ports:
        - containerPort: 80

---

# Service cho web1
apiVersion: v1
kind: Service
metadata:
  name: web1
spec:
  selector:
    app: web1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

# Deployment cho web2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: web2
        image: ttldlinhtm/web2:latest
        ports:
        - containerPort: 80

---

# Service cho web2
apiVersion: v1
kind: Service
metadata:
  name: web2
spec:
  selector:
    app: web2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
